openapi: 3.0.0
info:
  title: Smart Contract Manager API
  description: Smart Contract Manager API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: /
  - url: process.env.BACKPLANE_URL0
  - url: process.env.BACKPLANE_URL
  - url: process.env.BACKPLANE_URL2
  - url: process.env.BACKPLANE_URL3
    variables: {}
security:
  - bearerAuth: []
tags:
  - name: Agreement
    description: Contractual Agreement between Provider and Consumer.
paths:
  /template/{offering_id}:
    get:
      tags:
        - Agreement
      summary: Request template with static and dynamic parameters
      parameters:
        - name: offering_id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/template'
  /create_agreement_raw_transaction/{sender_address}:
    post:
      tags:
        - Agreement
      summary: Create agreement
      parameters:
        - name: sender_address
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/template' 
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/raw_transaction_template'
              example:
                nonce: 6
                to: "0x527F9771A4805E7E539436368D09ed5032bf8f57"
                from: "0xce02fe0c65285ac850d2e9b6494446e59f0b48e6"
                gasLimit: 12500000
                gasPrice: 10000000000
                chainId: 1337
                data: "0x89a8348c00000000000000000000000000000000000000000000000000000000000001c"
      security:
        - bearerAuth: []
  /sign_agreement_raw_transaction/{agreement_id}/{consumer_id}/{sender_address}:
    put:
      tags:
        - Agreement
      summary: Sign agreement 
      parameters:
        - name: agreement_id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: consumer_id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: sender_address
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/raw_transaction_template'
      security:
        - bearerAuth: []
  /update_agreement_raw_transaction/{agreement_id}/{sender_address}:
    put:
      tags:
        - Agreement
      summary: Update agreement 
      parameters:
        - name: agreement_id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: sender_address
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/template'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/raw_transaction_template'
      security:
        - bearerAuth: []      
  /get_agreement/{agreement_id}:
    get:
      tags:
        - Agreement
      summary: Get agreement
      parameters:
        - name: agreement_id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/agreement_template'
      security:
        - bearerAuth: []
  /check_active_agreements:
    get:
      tags:
        - Agreement
      summary: Check active agreements
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/active_agreements'
      security:
        - bearerAuth: []
  /check_agreements_by_consumer/{consumer_id}:
    get:
      tags:
        - Agreement
      summary: Check agreements by consumer
      parameters:
        - name: consumer_id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/active_agreements'
      security:
        - bearerAuth: []
  /check_agreements_by_provider/{provider_id}:
    get:
      tags:
        - Agreement
      summary: Check agreements by provider
      parameters:
        - name: provider_id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/active_agreements'
      security:
        - bearerAuth: []
  /get_state/{agreement_id}:
    get:
      tags:
        - Agreement
      summary: Get the state of the agreement
      parameters:
        - name: agreement_id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/state'
      security:
        - bearerAuth: []
  /deploy_signed_transaction:
    post:
      tags:
        - Agreement
      summary: Deploy signed transaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/signed_transaction'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transaction_object'
      security:
        - bearerAuth: []
components:
  schemas:
    state:
      type: object
      properties:
        state:
          type: string
    sign_msg:
      type: object
      properties:
        msg:
          type: string
    update_msg:
      type: object
      properties:
        msg:
          type: string
    agreement_id:
      type: object
      properties:
        agreement_id:
          type: string
    raw_transaction_template:
      type: object
      properties:
        nonce:
          type: integer
        to:
          type: string
        from:
          type: string
        gasLimit:
          type: integer
        gasPrice:
          type: integer
        chainId:
          type: integer
        data:
          type: string
    transaction_object:
        type: object
        properties:
          transactionHash:
            type: string
          transactionIndex:
            type: string
          blockHash:
            type: string
          contractAddress:
            type: string
          cumulativeGasUsed:
            type: integer
          to:
            type: string
          from:
            type: string
          gasUsed:
            type: integer
          logsBloom:
            type: string
          logs:
            type: array
            items: 
              type: object
          confirmation:
            type: integer
          status:
            type: integer     
    signed_transaction:
      type: object
      properties:
        signed_transaction:
          type: string
    template:
      type: object
      properties:
        DataOfferingDescription:
          type: object
          properties:
            dataOfferingId:
              type: string
            provider:
              type: string
            description:
              type: string
            title:
              type: string
            category:
              type: string
            isActive:
              type: boolean
        Purpose:
          type: string
        hasParties:
          type: object
          properties:
            Parties:
              type: object
              properties:
                dataProvider:
                  type: string
                dataConsumer:
                  type: string
        hasDuration:
          type: object
          properties:
            Duration:
              type: object
              properties:
                creationDate:
                  type: string
                startDate:
                  type: string
                endDate:
                  type: string
        hasDuties/Obligations:
          type: object
          properties:
            Duties/Obligations:
              type: object
              properties:
                qualityofData:
                  type: string
                characteristics:
                  type: array
                  items:
                    type: string
                dataAvailability:
                  type: boolean
        hasDescriptionOfData:
          type: object
          properties:
            DescriptionOfData:
              type: object
              properties:
                dataType:
                  type: string
                dataFormat:
                  type: string
                dataSource:
                  type: string
        hasIntendedUse:
          type: object
          properties:
            IntendedUse:
              type: object
              properties:
                processData:
                  type: boolean
                shareDataWithThirdParty:
                  type: boolean
                editData:
                  type: boolean
        hasLicenseGrant:
          type: object
          properties:
            LicenseGrant:
              type: object
              properties:
                copyData:
                  type: boolean
                transferable:
                  type: boolean
                exclusiveness:
                  type: boolean
                revocable:
                  type: boolean
        DataStream:
          type: boolean
    agreement_template:
      type: object
      properties:
        dataOfferingId:
          type: integer
        purpose:
          type: string
        state:
          type: integer
        providerId:
          type: string
        consumerId:
          type: string
        agreementDates:
          type: array
          items:
            type: integer
        descriptionOfData:
          type: object
          properties:
            dataType:
              type: string
            dataFormat:
              type: string
            dataSource:
              type: string
        intendedUse:
          type: object
          properties:
            processData:
              type: boolean
            shareDataWithThirdParty:
              type: boolean
            editData:
              type: boolean
        licenseGrant:
          type: object
          properties:
            copydata:
              type: boolean
            transferable:
              type: boolean
            exclusiveness:
              type: boolean
            revocable:
              type: boolean
        dataStream:
          type: boolean
        signed:
          type: boolean
        violation:
          type: array
          items:
            oneOf:
              - type: integer
              - type: string
              - type: object
                properties:
                  violationType:
                    type: integer
                  issuerId:
                    type: string
    active_agreements:
      type: array
      items:
        $ref: '#/components/schemas/agreement_template'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


